export const projects = [
    {
        title: "Soneraj Distributors",
        category: "Ecommerce & Inventory Management",
        desc: "A complete inventory management and ecommerce platform for tracking and selling liquor products with a seamless user experience. (Created for a client)",
        stack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Supabase Authentication"],
        bg: "from-white-600 via-gray-900 to-slate-600",
        year: "2026",
        image: "/Projects/soneraj-distributors.png",
        liveUrl: "https://soneraj-distributors-v2.vercel.app/",
        githubUrl: "",
        paid: "y"
    },
    {
        title: "Stock Sentiment Analysis",
        category: "Sentiment Analysis",
        desc: "A complete sentiment analysis platform for tracking and analyzing stock market data and news sentiments. This is my first AI project.",
        stack: ["Streamlit", "Python", "TensorFlow", "Pandas", "NumPy", "Scikit-learn", "Plotly", "VADER"],
        bg: "from-blue-600 via-indigo-600 to-violet-600",
        year: "2026",
        image: "/Projects/S-S-A.png",
        liveUrl: "https://stocksentimentanalysis.streamlit.app/",
        githubUrl: "https://github.com/Karan-Dayani/Stock_Sentiment_Analysis",
        paid: "n"
    },
    {
        title: "BODZ",
        category: "Affiliate Marketing",
        desc: "An affiliate website where users can find the best deals on Amazon products. (worked with the client's team on this project)",
        stack: ["Vite.js", "PostgreSQL", "AWS"],
        bg: "from-emerald-500 via-teal-600 to-cyan-600",
        year: "2024",
        image: "/Projects/BODZ.png",
        liveUrl: "https://best-online-dealz.vercel.app/",
        githubUrl: "https://github.com/arush789/Best-Online-Dealz",
        paid: "y"
    },
    {
        title: "Cravish",
        category: "Social Media",
        desc: "A social media platform for users to share their recipies online. (server might be off now)",
        stack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "Next Auth", "Firebase"],
        bg: "from-pink-600 via-rose-600 to-orange-500",
        year: "2024",
        image: "/Projects/cravish.png",
        liveUrl: "https://cravish.vercel.app/",
        githubUrl: "https://github.com/Karan-Dayani/Cravish",
        paid: "n"
    },
    {
        title: "BookShelf",
        category: "Library Management System",
        desc: "An online library management system where users can issue books with the permision of the admin, there is a fine system for delayed return. (server might be off now)",
        stack: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL", "Next Auth", "Firebase", "axios", "Express.js", "node.js"],
        bg: "from-amber-500 via-red-500 to-rose-600",
        year: "2025",
        image: "/Projects/bookshelf.png",
        liveUrl: "https://your-book-shelf.vercel.app/",
        githubUrl: "https://github.com/Karan-Dayani/BookShelf",
        paid: "n"
    },
    {
        title: "Binge It",
        category: "Entertainment",
        desc: "An entertainment platform where users can find new movies and can create there own custom watch lists.",
        bg: "from-rose-950 to-amber-500",
        stack: ["Vite.js", "TMDB API"],
        year: "2024",
        image: "/Projects/binge-it.png",
        liveUrl: "https://binge-it-mu.vercel.app/",
        githubUrl: "https://github.com/Karan-Dayani/BingeIt",
        paid: "n"
    },
    {
        title: "ShoeRack",
        category: "UI/UX Design",
        desc: "A Simple UI design for a shoe or an e-commerce website. (Really old project, not upto modern standards)",
        stack: ["HTML", "CSS"],
        bg: "from-amber-600 via-yellow-500 to-orange-600",
        year: "2023",
        image: "/Projects/shoeRack.png",
        liveUrl: "https://monumental-otter-4cd82d.netlify.app/",
        githubUrl: "https://github.com/Karan-Dayani/ShoeRack",
        paid: "n"
    },
];